### ISSUE TITLE
Missing BamConnectionManager

### ISSUE THREAD

**Issue by martonmiklos** [famez/J1939-Framework#3]
Hello @famez 

Many thanks for this great project!

I have tried to compile it, and it seems that a class called BamConnectionManager is missing. 

It is utilized in the Qt app here:
https://github.com/famez/J1939-Framework/blob/master/J1939Viewer/trcloader.cpp#L33

Could you please add it?
Thanks!

**Comment by famez** [comment]
Hi,

I abandoned the development of this tool one year ago, so it is not synchronized with the current status of the main library (J1939). 

The rest of the tools are up to date with the library, (j1939Decoder, j1939Sniffer, j1939Sender, j1939GUI, wireshark plugin...) in case that you want to use them...

Answering to your specific question, this class (BamConnectionManager) does not exists anymore in favor of BamReassembler class (J1939-Framework/J1939/Transport/BAM/BamReassembler.cpp), so that you can remove the lines concerning the class BamConnectionManager.

If you are interested in continuing the development of this tool, I can try make it compile again, but I am not working on it anymore...

**Comment by martonmiklos** [comment]
Hello,

Thanks for the feedback!
I am trying to implement a platform independent J1939 stack for a Qt based project, and your project quality rise my attention. I have already got it compiling I just wanted to make sure that the latest code is up at github. 

So do I understand that you are only focusing the J1939 library now and only the rest of the tools considered abandoned? If this is correct do you welcome PR for the tools?

**Comment by famez** [comment]
Everything is up to date except from J1939Viewer, unfortunately. You can make use of the rest of tools without any problem. They are working today ( as long as I tested ). 

Concerning Pull Requests, they are welcome for the tool J1939Viewer without any problem. In addition, if you would like to add a new functionality to the existing tools or create a new one, the work is welcome.
